require 'hoe'
require './lib/sportdb/version.rb'

Hoe.spec 'sportdb' do
  
  self.version = SportDB::VERSION
  
  self.summary = 'sportdb - sport.db command line tool'
  self.description = summary

  self.urls    = ['http://geraldb.github.com/sport.db']
  
  self.author  = 'Gerald Bauer'
  self.email   = 'opensport@googlegroups.com'
    
  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.markdown'
  self.history_file = 'History.markdown'
  
  self.extra_deps = [
    ['activerecord', '~> 3.2'],  # NB: will include activesupport,etc.
    ['worlddb', '~> 0.2.0']
    ### ['sqlite3',      '~> 1.3']  # NB: install on your own; remove dependency
  ]

  self.post_install_message =<<EOS
******************************************************************************

Questions? Comments? Send them along to the mailing list.
https://groups.google.com/group/opensport

******************************************************************************
EOS
  
end